Show interactive menu and update interface.

diff --git a/4_osprep/osprep b/4_osprep/osprep
--- a/4_osprep/osprep
+++ b/4_osprep/osprep
@@ -19,6 +19,13 @@ NC="\033[0m"
 BOLD="\033[1m"
 GREEN="\033[0;32m"
 
+DIALOG_OK=0
+DIALOG_CANCEL=1
+DIALOG_HELP=2
+DIALOG_EXTRA=3
+DIALOG_ITEM_HELP=4
+DIALOG_ESC=255
+
 OPT_FORMAT="text"
 OPT_LOCAL=false
 REPO_URL="http://charlotte.celones.pl/osprep/"
@@ -40,6 +47,13 @@ function check_make {
   fi
 }
 
+function check_dialog {
+  if [ -z `command -v dialog` ]; then
+    echo "This command requires dialog utility, but it hasn't been found!" >&2
+    exit 1
+  fi
+}
+
 ##################### Wrappers for Wget ####################
 function http_header {
   # $URL - remote resource
@@ -56,15 +70,30 @@ function http_download {
 }
 
 function download_gauge {
-  # $URL  - remote resource
-  # $FILE - output file name
+  # $URL   - remote resource
+  # $FILE  - output file name
+  # $TITLE - dialog title
   wget --progress=dot -U "$HTTP_USER_AGENT" -O "$FILE" "$URL" 2>&1 \
   | grep "%" | sed -u -e 's/^ *[^ ]\+[\. ]\+//g' | sed -u -e 's/%.*//' \
   | dialog \
   --backtitle "$PROGRAM_NAME" \
-  --title "Downloading" \
-  --gauge "$URL" 10 100
+  --title "$TITLE" \
+  --gauge "Downloading $URL..." 10 60
   if [ $? -ne 0 ]; then rm -f "$FILE"; fi
+}
+
+function update_needed {
+  # $FILE - candidate for update
+  if [ ! -f "$FILE" ]; then
+    true
+  else
+    HTTP_LAST_MODIFIED=`http_header "Last-Modified"`
+    if [ $(date -d "$HTTP_LAST_MODIFIED" +%s) -gt $(stat -c %Y "$FILE") ]; then
+      true
+    else
+      false
+    fi
+  fi
 }
 
 ############## Package name<->path converters ##############
@@ -287,28 +316,17 @@ function beautify_settings {
   done
 }
 
-################################### COMMANDS ###################################
-##### Open interactive dialog-based UI
-function interactive {
-  tput smcup
-
-  RESULT=`dialog \
-  --backtitle "$PROGRAM_NAME" \
-  --title "Build List Box" \
-  --visit-items \
-  --buildlist "Text" 0 0 0 \
-    "it1" "Initially selected"     on \
-    "it2" "Initially not selected" off 2>&1 1>&3`
-
+function simple_msgbox {
+  # $1 - title
+  # $2 - text
   dialog \
-  --backtitle "$PROGRAM_NAME" \
-  --title "Message Box" \
-  --msgbox "You've selected: $RESULT" 0 0
-
-  tput rmcup
-
+    --backtitle "$PROGRAM_NAME" \
+    --title "$1" \
+    --clear \
+    --msgbox "$2" 10 60
 }
 
+################################### COMMANDS ###################################
 ##### Show version information
 function version {
   echo $PROGRAM_NAME
@@ -337,25 +355,41 @@ function update {
 
   mkdir -p `dirname "$FILE"`
 
-  if [ -f "$FILE" ]; then
-    HTTP_LAST_MODIFIED=`http_header "Last-Modified"`
-    if [ $(date -d "$HTTP_LAST_MODIFIED" +%s) -gt $(stat -c %Y "$FILE") ]; then
-      rm "$FILE"
+  if [ $IOPT_DIALOG == false ]; then
+
+    if update_needed; then
+      echo "Updating the repository..."
+      http_download 2>&1
+      if [ -f "$FILE" ]; then
+        echo "Repository update completed."
+      else
+        echo "Cannot update repository!" >&2
+        exit 1
+      fi
+
     else
       echo "Repository already up to date."
     fi
+
+  else
+
+    if update_needed; then
+      TITLE="Repository update" download_gauge
+      if [ -f "$FILE" ]; then
+        simple_msgbox "Repository update" "Repository update completed."
+      else
+        simple_msgbox "Repository update" "Cannot update repository!"
+        exit 1
+      fi
+
+    else
+      simple_msgbox "Repository update" "Repository already up to date."
+    fi
+
+
   fi
 
-  if [ ! -f "$FILE" ]; then
-    echo "Updating the repository..."
-    http_download
-    if [ -f "$FILE" ]; then
-      echo "Repository update completed."
-    else
-      echo "Cannot update repository!" >&2
-      exit 1
-    fi
-  fi
+  
 }
 
 ##### Show available base packages
@@ -721,10 +755,78 @@ function image {
   return
 }
 
-######################### SCRIPT ARGUMENTS PROCESSING ##########################
-exec 3>&1
+##### Open interactive dialog-based UI
+function interactive {
+  check_dialog
 
+  tput smcup
+
+  while true; do
+    exec 3>&1
+    ITEM=`dialog \
+      --backtitle "$PROGRAM_NAME" \
+      --title "Menu" \
+      --clear \
+      --cancel-label "Exit" \
+      --menu "Please select:" 0 0 4 \
+      1 "Update base packages list" \
+      2 "Change remote repository address" \
+      3 "Display Home Space Utilization" \
+      2>&1 1>&3`
+    RVAL=$?
+    exec 3>&-
+
+    case $RVAL in
+      $DIALOG_CANCEL ) break  ;;
+      $DIALOG_ESC    ) exit 1 ;;
+    esac
+
+    case $ITEM in
+      0)
+        break
+        ;;
+
+      1)
+        IOPT_DIALOG=true update
+        ;;
+      2)
+        exec 3>&1
+        INPUT=`dialog \
+          --backtitle "$PROGRAM_NAME" \
+          --title "Change remote repository" \
+          --inputbox "Type in a new remote repository URL:" 10 60 "$REPO_URL" \
+          2>&1 1>&3`
+        RVAL=$?
+        exec 3>&-
+
+        case $RVAL in
+          $DIALOG_CANCEL ) break  ;;
+          $DIALOG_ESC    ) exit 1 ;;
+        esac
+
+        IOPT_DIALOG=true update "$INPUT"
+        ;;
+      3)
+        exit
+        ;;
+    esac
+  done
+
+  #RESULT=`dialog \
+  #--backtitle "$PROGRAM_NAME" \
+  #--title "Build List Box" \
+  #--visit-items \
+  #--buildlist "Text" 0 0 0 \
+  #  "it1" "Initially selected"     on \
+  #  "it2" "Initially not selected" off 2>&1 1>&3`
+
+  tput rmcup
+
+}
+
+######################### SCRIPT ARGUMENTS PROCESSING ##########################
 if [ -f "${REPO_LOCAL}remote" ]; then REPO_URL=`cat ${REPO_LOCAL}remote`; fi
+if [ -z $IOPT_DIALOG ]; then IOPT_DIALOG=false; fi
 
 for i in "$@"; do
   case $i in
